### PR TITLE
Fixes not being able to build in release mode

### PR DESCRIPTION
**Pull request by asselin**
Cordova is expecting an options object, not an options array

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Is this a breaking change? It works for me so not sure, have to investigate. Can you point me to the docs or page where you found that information?

**Comment by asselin** [comment]
Looks like it may have been changed in 5.4.0.  Take a look at https://github.com/apache/cordova-lib/blame/master/cordova-lib/src/platforms/PlatformApiPoly.js#L506  The getBuildArgs() function is expecting an object instead of an array  for options.  The commit is tagged as 5.4.0

**Comment by asselin** [comment]
Also, take a look here, which calls the above: https://github.com/apache/cordova-lib/commit/07271a5c6162c0b2bee55e1ea23f91ebdfbbb34c#diff-8b02e5c6653bdda30028a4d0333d44abL37

options used to be passed to superspawn, but now instead is going through the getBuildArgs() function.

**Comment by SamVerschueren** [comment]
Thanks for the information, will look at it tomorrow. If not, don't hesitate to ping me back :).

**Comment by WuglyakBolgoink** [comment]
@SamVerschueren  PING ;)

**Comment by SamVerschueren** [comment]
I finally looked into this. I never experienced issues with the array approach, what we have today. So I tried out the object approach and it did work. However, since this PR another option was added, namely the [`buildMethod`](https://github.com/SamVerschueren/gulp-cordova-build-android/blob/master/index.js#L62-L66). I tried adding those to the object with `options.ant = true` but it did not work, it always used `gradle`.

So I dived into the code of `cordova-lib` itself and it's still perfectly possible to pass down an array because the array is being parsed first by [this method](https://github.com/apache/cordova-lib/blob/master/cordova-lib/src/cordova/util.js#L316). So both options are valid.

Sorry for replying so late. I really never came to diving into this because it always worked for me.

**Pull request closed without merging**
