### PR TITLE
Merge with latest changes, bump up to cordova 6.1.1 and add the possibility to choose cordova-android version

### PR DESCRIPTION
**Pull request by JoMas971**

### CODE REVIEW

**Comment by JoMas971** [comment]
I've bumped up the cordova-lib version to the latest 6.1.1 (since it fixes a lot of issues) and also, i've added the possibility to choose the version of the cordova-android cordova platform.

**Comment by SamVerschueren** [comment]
You pushed merge conflicts.

**Comment by JoMas971** [comment]
@SamVerschueren normally it is fixed now, isn't it ?

**Comment by SamVerschueren** [comment]
Press the `Files Changed` tabs and you'll see what I mean. Also the indentation changed from `tabs` to `spaces`.

**Comment by SamVerschueren** [comment]
I'd rather see 2 separate PR's for this though. Willing to do that? If not, no problem. But then you can start with a clean fork without merge conflicts.

**Comment by JoMas971** [comment]
ho yeah ! I didn't noticed that, sorry. Well, let me to re-fork and makes the change and PR again. I agree, there is to many commits/merge it this.

**Pull request closed without merging**
